export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const FETCH_TESTIMONIALS = "FETCH_TESTIMONIALS";
export const FETCH_TESTIMONIALS_SUCCESS = "FETCH_TESTIMONIALS_SUCCESS";
export const FETCH_TESTIMONIALS_ERROR = "FETCH_TESTIMONIALS_ERROR";

export const VISIBILITY_FILTERS: any = {
  ALL: "all",
  COMPLETED: "completed",
  INCOMPLETE: "incomplete",
};
